version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    restart: always
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    depends_on:
      - mongo-database
    networks:
      - ${GLOBAL_NETWORK:-services}

  mongo-database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - ${GLOBAL_NETWORK:-services}

  mysql-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
    volumes:
      - mysqldb-data:/var/lib/mysql
    networks:
      - ${GLOBAL_NETWORK:-services}

volumes:
  mysqldb-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/mysqldb/data
      o: bind
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/mongodb/data
      o: bind
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/axonserver/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/axonserver/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES}/axonserver/config
      o: bind