server:
  port: 9092
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: p@ssw0rd

security:
  oauth2:
    resource:
      jwt:
        key-value: uWlyN0gXhnUPEO2fwUx8jWb2qFgpsVyu