server:
  port: 9091
spring:
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017

security:
  oauth2:
    resource:
      jwt:
        key-value: uWlyN0gXhnUPEO2fwUx8jWb2qFgpsVyu